### ISSUE TITLE
无法build

### ISSUE THREAD

**Issue by guolingege** [tobe-fe-dalao/fast-vue3#63]
```console
/usr/local/bin/yarn run build
yarn run v1.22.19
$ vue-tsc --noEmit && vite build
[unocss] `exclude` option is deprecated, use `content.pipeline.exclude` instead.
Building [██████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 15% | Time: 0.1sBrowserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Building [██████████████████████████░░░░░░░░░░░░░░] 65% | Time: 16.8s
Build failed. Please check the error message

error during build:
RollupError: "hasInjectionContext" is not exported by "node_modules/.pnpm/vue-demi@0.14.6_vue@3.2.47/node_modules/vue-demi/lib/index.mjs", imported by "node_modules/.pnpm/pinia@2.1.6_typescript@5.0.4_vue@3.2.47/node_modules/pinia/dist/pinia.mjs".
    at error (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
    at Module.error (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:13452:16)
    at Module.traceVariable (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:13863:29)
    at ModuleScope.findVariable (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:12418:39)
    at ReturnValueScope.findVariable (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:6966:38)
    at Identifier.bind (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:8116:40)
    at CallExpression.bind (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:5739:23)
    at CallExpression.bind (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:9669:15)
    at LogicalExpression.bind (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:5739:23)
    at LogicalExpression.bind (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:5739:23)
    at ArrowFunctionExpression.bind (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:5739:23)
    at VariableDeclarator.bind (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:5739:23)
    at VariableDeclaration.bind (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:5735:28)
    at Program.bind (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:5735:28)
    at Module.bindReferences (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:13448:18)
    at Graph.sortModules (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:24860:20)
    at Graph.build (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:24744:14)
    at async file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:25761:13
    at async catchUnfinishedHookActions (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:24914:20)
    at async rollupInternal (file:///Users/******/fast-vue3/node_modules/.pnpm/rollup@3.21.5/node_modules/rollup/dist/es/shared/node-entry.js:25756:5)
    at async build (file:///Users/******/fast-vue3/node_modules/.pnpm/vite@4.3.9_@types+node@18.15.11_less@4.1.3/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46471:18)
    at async CAC.<anonymous> (file:///Users/******/fast-vue3/node_modules/.pnpm/vite@4.3.9_@types+node@18.15.11_less@4.1.3/node_modules/vite/dist/node/cli.js:812:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
```

**Comment by GDY-2000** [comment]
可以使用build:pro试试
