### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by SaoXuan** [tobe-fe-dalao/fast-vue3#66]
```shell
PS E:\web-project\fast-vue3> pnpm i
Scope: all 2 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +1549
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  
Progress: resolved 1549, reused 1547, downloaded 0, added 1549, done
node_modules/.pnpm/esbuild@0.14.36/node_modules/esbuild: Running postinstall script, done in 416ms
node_modules/.pnpm/esbuild@0.17.12/node_modules/esbuild: Running postinstall script, done in 357ms
node_modules/.pnpm/esbuild@0.14.21/node_modules/esbuild: Running postinstall script, done in 314ms

dependencies:
+ @ant-design/icons-vue 6.1.0  
+ @devui-design/icons 1.3.0    
+ @element-plus/icons-vue 2.1.0
+ @idux/cdk 1.9.4
+ @idux/components 1.12.2      
+ @idux/pro 1.12.2
+ @vueuse/components 10.6.1    
+ @vueuse/core 10.6.1
+ ant-design-vue 3.2.19        
+ axios 1.4.0
+ dayjs 1.11.8
+ devui-theme 0.0.4
+ echarts 5.4.2
+ element-plus 2.4.2
+ mitt 3.0.0
+ naive-ui 2.34.3
+ pinia 2.1.7
+ pinia-plugin-persistedstate 3.1.0
+ qs 6.11.1
+ tdesign-vue-next 1.7.0
+ vue 3.2.47
+ vue-devui 1.6.0
+ vue-router 4.2.2

devDependencies:
+ @arco-design/web-vue 2.53.2
+ @commitlint/cli 17.8.1
+ @commitlint/config-conventional 17.8.1
+ @types/node 18.15.11
+ @types/nprogress 0.2.0
+ @types/qs 6.9.7
+ @typescript-eslint/eslint-plugin 5.62.0
+ @typescript-eslint/parser 5.62.0
+ @vitejs/plugin-vue 4.2.0
+ @vitejs/plugin-vue-jsx 3.0.1
+ autoprefixer 10.4.14
+ cz-git 1.7.1
+ eslint 8.54.0
+ eslint-config-prettier 8.8.0
+ eslint-define-config 1.24.1
+ eslint-plugin-import 2.29.0
+ eslint-plugin-prettier 4.2.1
+ eslint-plugin-simple-import-sort 10.0.0
+ eslint-plugin-vue 9.18.1
+ husky 8.0.3
+ import 0.0.6
+ less 4.1.3
+ less-loader 11.1.3
+ lint-staged 13.2.2
+ mockjs 1.1.0
+ nprogress 0.2.0
+ plop 3.1.2
+ postcss 8.4.24
+ postcss-html 1.5.0
+ postcss-less 6.0.0
+ postcss-px-to-viewport 1.1.1
+ postcss-scss 4.0.9
+ prettier 2.8.8
+ rollup-plugin-visualizer 5.9.2
+ stylelint 15.11.0
+ stylelint-config-recommended 12.0.0
+ stylelint-config-recommended-vue 1.4.0
+ stylelint-config-standard 33.0.0
+ stylelint-order 6.0.3
+ stylelint-prettier 3.0.0
+ typescript 5.0.4
+ unocss 0.53.6
+ unplugin-auto-import 0.16.4
+ unplugin-icons 0.16.3
+ unplugin-vue-components 0.25.1
+ unplugin-vue-router 0.6.4
+ vite 4.3.9
+ vite-plugin-compression 0.5.1
+ vite-plugin-html 3.2.0
+ vite-plugin-imagemin 0.6.1
+ vite-plugin-mkcert 1.17.1
+ vite-plugin-mock 3.0.0
+ vite-plugin-progress 0.0.7
+ vite-plugin-restart 0.3.1
+ vite-plugin-style-import 2.0.0
+ vite-plugin-svg-icons 2.0.1
+ vite-plugin-vue-images 0.6.1
+ vite-plugin-vue-setup-extend 0.4.0
+ vue-eslint-parser 9.3.2
+ vue-tsc 1.8.22

. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 255ms
Done in 19.2s
PS E:\web-project\fast-vue3> pnpm dev

> fast-vue3@0.1.2 dev E:\web-project\fast-vue3
> vite --mode development

[unocss] `exclude` option is deprecated, use `content.pipeline.exclude` instead.
[unocss] `exclude` option is deprecated, use `content.pipeline.exclude` instead.

  VITE v4.3.9  ready in 3093 ms

  ➜  Local:   https://localhost:3000/
  ➜  Network: https://192.168.124.222:3000/
  ➜  Network: https://192.168.56.1:3000/
  ➜  Network: https://192.168.58.1:3000/
  ➜  Network: https://192.168.74.1:3000/
  ➜  press h to show help
X [ERROR] No matching export in "node_modules/.pnpm/vue-demi@0.14.6_vue@3.2.47/node_modules/vue-demi/lib/index.mjs" for import "hasInjectionContext"

    node_modules/.pnpm/pinia@2.1.7_typescript@5.0.4_vue@3.2.47/node_modules/pinia/dist/pinia.mjs:6:9:
      6 │ import { hasInjectionContext, inject, toRaw, watch, unref, markRaw, effectScope, ref, isVue2, isRef, isReactive, set, getCurrentScope, onScopeDispose, getCurrentInstance, reactive, toRef, del, nextTick, computed, toRefs } fr...
        ╵          ~~~~~~~~~~~~~~~~~~~

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
E:\web-project\fast-vue3\node_modules\.pnpm\esbuild@0.17.12\node_modules\esbuild\lib\main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/.pnpm/pinia@2.1.7_typescript@5.0.4_vue@3.2.47/node_modules/pinia/dist/pinia.mjs:6:9: ERROR: No matching export in "node_modules/.pnpm/vue-demi@0.14.6_vue@3.2.47/node_modules/vue-demi/lib/index.mjs" for import "hasInjectionContext"
    at failureErrorWithLog (E:\web-project\fast-vue3\node_modules\.pnpm\esbuild@0.17.12\node_modules\esbuild\lib\main.js:1636:15)
    at E:\web-project\fast-vue3\node_modules\.pnpm\esbuild@0.17.12\node_modules\esbuild\lib\main.js:1048:25
    at E:\web-project\fast-vue3\node_modules\.pnpm\esbuild@0.17.12\node_modules\esbuild\lib\main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 9,
        file: 'node_modules/.pnpm/pinia@2.1.7_typescript@5.0.4_vue@3.2.47/node_modules/pinia/dist/pinia.mjs',
        length: 19,
        line: 6,
        lineText: "import { hasInjectionContext, inject, toRaw, watch, unref, markRaw, effectScope, ref, isVue2, isRef, isReactive, set, getCurrentScope, onScopeDispose, getCurrentInstance, reactive, toRef, del, nextTick, computed, toRefs } from 'vue-demi';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/.pnpm/vue-demi@0.14.6_vue@3.2.47/node_modules/vue-demi/lib/index.mjs" for import "hasInjectionContext"'
    }
  ],
  warnings: []
}

Node.js v19.8.1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by wqsvkem** [comment]
和你一样的问题， 换node 18 和20的也都不行

**Comment by fonghehe** [comment]
什么环境下，给个参数
